### ISSUE TITLE
草泥马 傻逼 狗日的 滚

### ISSUE THREAD

**Issue by kuailezhiyuan** [boycott-fuck-xuexiqiangguo/Boycott-Fuck-XueXiQiangGuo#106]
草泥马 傻逼 狗日的 滚

**Comment by kuailezhiyuan** [comment]
程序员中的傻逼 败类

**Comment by SaveMyAss** [comment]
> 程序员中的傻逼 败类

别侮辱程序员好吗，我们甚至都不知道它是不是程序员。（叹气）

**Comment by KOTOWARU17** [comment]
这种害人的东西能report给GitHub？

**Comment by Zeyu-W** [comment]
听党指挥！能打胜仗！作风优良！你们这些人就是欠一顿社会主义的毒打！

**Comment by unknowndevQwQ** [comment]
> > 程序员中的傻逼 败类
> 
> 别侮辱程序员好吗，我们甚至都不知道它是不是程序员。（叹气）

但是它不是程序员，它是 `jvabo` 大佐
我太熟悉它的言行举止的风格了
