### ISSUE TITLE
*****************

### ISSUE THREAD

**Issue by ScSofts** [boycott-fuck-xuexiqiangguo/Boycott-Fuck-XueXiQiangGuo#134]
****************

**Comment by ScSofts** [comment]
正义算什么，存在、发展才是硬道理！

**Comment by WittXie** [comment]
兄弟，出国吧

**Comment by unknowndevQwQ** [comment]
> 你是程序员不，你CEF用过没，好用不？
> CEF的文档、项目主页、SVN、Git服务器都被墙了
> 你敢说你没翻墙？！！！！
> 彻彻底底的闭关锁国、把先进技术拒之门外！

这个仓库的持有者是恶名昭著的 `jvbao` 大佐
可以使用 `google` 来检索它的许多恶行
